<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\demo.datalayer\demo.datalayer.csproj" />
    <ProjectReference Include="..\WebApplication5\WebApplication5.csproj" />
  </ItemGroup>

</Project>
